name : ms-immobilier
services:
  # mysql Container ---------------------------------------------------------
  ms-mysql:
    image: mysql:8.2.0
    container_name: ms-mysql
    volumes:
      - ./MS-API/init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 3306:3306
    expose:
      - 3306
    healthcheck:
      test: [ 'CMD', 'mysqladmin', 'ping', '-h', 'localhost' ]
      interval: 5s
      timeout: 10s
      retries: 5
  # keycloak Container ------------------------------------------------------
  ms-keycloak:
    image: quay.io/keycloak/keycloak:23.0.5
    container_name: ms-keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 9090:8080
    expose:
      - 9090
    command:
      - start-dev
  # discovery-service Container ---------------------------------------------
  ms-discovery:
    build: ./MS-API/discovery-service
    container_name: ms-discovery
    ports:
      - 8761:8761
    expose:
      - 8761
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 10s
      retries: 5
  # config-service Container ------------------------------------------------
  ms-config:
    build: ./MS-API/config-service
    container_name: ms-config
    environment:
      - DISCOVERY_SERVICE_URL=http://ms-discovery:8761/eureka
    ports:
      - 9999:9999
    expose:
      - 9999
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9999/actuator/health" ]
      interval: 10s
      retries: 5
    depends_on:
      ms-discovery:
        condition: service_healthy
  # appartement-service Container ------------------------------------------
  ms-appartement:
    build: ./MS-API/appartement-service
    container_name: ms-appartement
    environment:
      - CONFIG_SERVICE=http://ms-config:9999
      - DISCOVERY_SERVICE_URL=http://ms-discovery:8761/eureka
      - DB_URL=jdbc:mysql://ms-mysql:3306/appartement_service
      - DB_USER=root
      - DB_PASSWORD=
      - KEYCLOAK_ISSUER_URI=http://ms-keycloak:9090/realms/MS-IMMOBILIER
      - KEYCLOAK_CERT=http://localhost:9090/realms/MS-IMMOBILIER/protocol/openid-connect/certs
    ports:
      - 8081:8081
    expose:
      - 8081
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
      interval: 10s
      retries: 5
    depends_on:
        ms-config:
            condition: service_healthy
        ms-mysql:
            condition: service_healthy
  # client-service Container ------------------------------------------------
  ms-client:
    build: ./MS-API/client-service
    container_name: ms-client
    environment:
      - CONFIG_SERVICE=http://ms-config:9999
      - DISCOVERY_SERVICE_URL=http://ms-discovery:8761/eureka
      - DB_URL=jdbc:mysql://ms-mysql:3306/client_service
      - DB_USER=root
      - DB_PASSWORD=
      - KEYCLOAK_ISSUER_URI=http://ms-keycloak:9090/realms/MS-IMMOBILIER
      - KEYCLOAK_CERT=http://localhost:9090/realms/MS-IMMOBILIER/protocol/openid-connect/certs
    ports:
      - 8082:8082
    expose:
      - 8082
    depends_on:
      ms-appartement:
        condition: service_healthy
  # reservation-service Container -------------------------------------------
  ms-reservation:
    build: ./MS-API/reservation-service
    container_name: ms-reservation
    environment:
      - CONFIG_SERVICE=http://ms-config:9999
      - DISCOVERY_SERVICE_URL=http://ms-discovery:8761/eureka
      - DB_URL=jdbc:mysql://ms-mysql:3306/reservation_service
      - DB_USER=root
      - DB_PASSWORD=
      - KEYCLOAK_ISSUER_URI=http://ms-keycloak:9090/realms/MS-IMMOBILIER
      - KEYCLOAK_CERT=http://localhost:9090/realms/MS-IMMOBILIER/protocol/openid-connect/certs
    ports:
      - 8083:8083
    expose:
      - 8083
    depends_on:
      ms-appartement:
        condition: service_healthy
  # gateway-service Container -------------------------------------------
  ms-gateway:
    build: ./MS-API/gateway-service
    container_name: ms-gateway
    environment:
      - DISCOVERY_SERVICE_URL=http://ms-discovery:8761/eureka
    ports:
      - 8888:8888
    expose:
      - 8888
    depends_on:
      ms-discovery:
        condition: service_healthy